// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqjVMJ_Q94JGDmrDV4pSn-S1CPmkKoyQo',
    appId: '1:466818250020:web:06b8f4dc7d793d7b366fb1',
    messagingSenderId: '466818250020',
    projectId: 'ezmoneymobilebank',
    authDomain: 'ezmoneymobilebank.firebaseapp.com',
    storageBucket: 'ezmoneymobilebank.appspot.com',
    measurementId: 'G-76QZR29JCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV4sF1d031vVI_DedMyDVEawXJ5xFv94s',
    appId: '1:466818250020:android:2e77e09e56ee622f366fb1',
    messagingSenderId: '466818250020',
    projectId: 'ezmoneymobilebank',
    storageBucket: 'ezmoneymobilebank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUB708aX45_YShaqj6_hv8IrUaGFSe_ic',
    appId: '1:466818250020:ios:c3aeb79f3c0c6142366fb1',
    messagingSenderId: '466818250020',
    projectId: 'ezmoneymobilebank',
    storageBucket: 'ezmoneymobilebank.appspot.com',
    iosBundleId: 'com.example.ezmoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUB708aX45_YShaqj6_hv8IrUaGFSe_ic',
    appId: '1:466818250020:ios:97e006fdfbed885f366fb1',
    messagingSenderId: '466818250020',
    projectId: 'ezmoneymobilebank',
    storageBucket: 'ezmoneymobilebank.appspot.com',
    iosBundleId: 'com.example.ezmoney.RunnerTests',
  );
}
